# Generated by Django 2.2.9 on 2021-04-09 04:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("posts", "0002_auto_20210409_1132"),
    ]

    operations = [
        migrations.AlterField(
            model_name="group",
            name="title",
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
