# Generated by Django 2.2.9 on 2021-04-09 13:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("posts", "0003_auto_20210409_1203"),
    ]

    operations = [
        migrations.RenameField(
            model_name="post",
            old_name="groupe",
            new_name="group",
        ),
    ]
