# Generated by Django 2.2.6 on 2021-06-16 13:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("posts", "0005_auto_20210610_2059"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="post",
            options={"ordering": ["-pub_date"], "verbose_name_plural": "Посты"},
        ),
        migrations.DeleteModel(
            name="PostForm",
        ),
    ]
