# Generated by Django 2.2.6 on 2021-09-12 02:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("posts", "0010_auto_20210909_0643"),
    ]

    operations = [
        migrations.AlterField(
            model_name="post",
            name="pub_date",
            field=models.DateTimeField(
                auto_now_add=True, db_index=True, verbose_name="date published"
            ),
        ),
    ]
